apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentrilite
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sentrilite-read
rules:
# Core objects for OOMKilled/pod/node watching
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
# Metrics API for high CPU polling
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sentrilite-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sentrilite-read
subjects:
- kind: ServiceAccount
  name: sentrilite
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sentrilite-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: sentrilite-agent
  template:
    metadata:
      labels:
        app: sentrilite-agent
    spec:
      serviceAccountName: sentrilite
      automountServiceAccountToken: true

      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      tolerations:
      - operator: Exists

      # Optional: keep if your image is amd64-only
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux

      containers:
      - name: sentrilite
        image: docker.io/sentrilite/sentrilite:1.0.2
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: http
          containerPort: 80
        - name: ws
          containerPort: 8765
        volumeMounts:
        # eBPF + tracing mounts
        - name: bpf
          mountPath: /sys/fs/bpf
        - name: kdebug
          mountPath: /sys/kernel/debug
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        - name: kernel-src
          mountPath: /usr/src
          readOnly: true

        lifecycle:
        # Uninstall: Remove all tracepoints and bpfmaps
          preStop:
            exec:
              command: ["/bin/sh","-c","/opt/sentrilite/unload_bpf.sh || true"]

      volumes:
      - name: bpf
        hostPath:
          path: /sys/fs/bpf
      - name: kdebug
        hostPath:
          path: /sys/kernel/debug
      - name: modules
        hostPath:
          path: /lib/modules
      - name: kernel-src
        hostPath:
          path: /usr/src

