apiVersion: v1
kind: Secret
metadata:
  name: sentrilite-integrations
  namespace: kube-system
type: Opaque
stringData:
  PAGERDUTY_ROUTING_KEY: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sentrilite-config
  namespace: kube-system
data:
  PAGERDUTY_EVENTS_URL: ""
  ALERTMANAGER_URL: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentrilite
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sentrilite-read
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sentrilite-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sentrilite-read
subjects:
- kind: ServiceAccount
  name: sentrilite
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sentrilite-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: sentrilite-agent
  template:
    metadata:
      labels:
        app: sentrilite-agent
    spec:
      serviceAccountName: sentrilite
      automountServiceAccountToken: true

      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - operator: Exists
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux

      containers:
      - name: sentrilite
        image: docker.io/sentrilite/sentrilite:1.0.8
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SENTRILITE_LICENSE_PATH
          value: /opt/sentrilite/license.key
        # from Secret (sensitive)
        - name: PAGERDUTY_ROUTING_KEY
          valueFrom:
            secretKeyRef:
              name: sentrilite-integrations
              key: PAGERDUTY_ROUTING_KEY
        # from ConfigMap (non-sensitive)
        - name: PAGERDUTY_EVENTS_URL
          valueFrom:
            configMapKeyRef:
              name: sentrilite-config
              key: PAGERDUTY_EVENTS_URL
              optional: true
        - name: ALERTMANAGER_URL
          valueFrom:
            configMapKeyRef:
              name: sentrilite-config
              key: ALERTMANAGER_URL
              optional: true
        ports:
        - name: http
          containerPort: 80
        - name: ws
          containerPort: 8765
        volumeMounts:
        # Overlay only the file; keeps the rest of /opt/sentrilite from the image
        - name: sentrilite-license
          mountPath: /opt/sentrilite/license.key
          subPath: license.key
          readOnly: true
        # eBPF + tracing mounts
        - name: bpf
          mountPath: /sys/fs/bpf
        - name: kdebug
          mountPath: /sys/kernel/debug
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        - name: kernel-src
          mountPath: /usr/src
          readOnly: true
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","/opt/sentrilite/unload_bpf.sh || true"]

      volumes:
      # Kustomize will inject the hash-suffixed Secret name here automatically
      - name: sentrilite-license
        secret:
          secretName: sentrilite-license
          defaultMode: 0400
      - name: bpf
        hostPath: { path: /sys/fs/bpf }
      - name: kdebug
        hostPath: { path: /sys/kernel/debug }
      - name: modules
        hostPath: { path: /lib/modules }
      - name: kernel-src
        hostPath: { path: /usr/src }
